### ISSUE TITLE
Solid effort! I have had to go private on my micro endeavors.. 

### ISSUE THREAD

**Issue by ShoGinn** [ddday/micro#1]
Very cool effort man! I would love to keep in contact with you in case MS decides you are a threat ;) let me know.

**Comment by jjjchens235** [comment]
ShoGinn- the original author of this program is Charles Bel. His repo is [here](https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues), in case you still want to get in contact with him. He just made an update to the program too.

**Comment by ShoGinn** [comment]
Thanks! Glad you were able to sleuth out the code! I know I had referenced this code since it wasn't a 'fork' and didn't inquire further.
